"use client";

import React, { useState } from "react";
import { AssessmentReport } from "@/lib/api";
import { Award, CheckCircle, AlertCircle, Calendar, Download, RefreshCw, ArrowRight, BookCheck } from "lucide-react";

interface AnalyticsViewProps {
  report: AssessmentReport;
  onRestart: () => void;
}

export const AnalyticsView: React.FC<AnalyticsViewProps> = ({ report, onRestart }) => {
  const [completedDays, setCompletedDays] = useState<number[]>([]);

  const toggleDay = (day: number) => {
    setCompletedDays((prev) =>
      prev.includes(day) ? prev.filter((d) => d !== day) : [...prev, day]
    );
  };

  const handleDownloadNotes = () => {
    const textContent = `
AETHERIS AI TEACHER - MASTERY REPORT & SUMMARY NOTES
==================================================
Topic: ${report.topic}
Final Mastery Score: ${report.score_percentage}%
Total Evaluated Concepts: ${report.total_questions}

STRONG MASTERY AREAS:
${report.strong_concepts.map((c) => `✓ ${c}`).join("\n")}

IDENTIFIED WEAK CONCEPTS & MISCONCEPTIONS:
${report.weak_concepts.length ? report.weak_concepts.map((c) => `- ${c}`).join("\n") : "None! Perfect Mastery"}

PEDAGOGICAL RECOMMENDATION:
${report.revision_recommendation}

7-DAY PERSONALIZED SPACED REPETITION PLAN:
${report.seven_day_plan.map((p) => `Day ${p.day}: ${p.task}`).join("\n")}
==================================================
Generated by Aetheris Autonomous Multimodal AI Educator
`;

    const blob = new Blob([textContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Aetheris_Notes_${report.topic.replace(/\s+/g, "_")}.txt`;
    link.click();
  };

  return (
    <div className="w-full max-w-4xl bg-slate-900/95 border border-cyan-500/30 rounded-3xl p-8 md:p-10 shadow-2xl backdrop-blur-xl animate-in fade-in duration-300">
      {/* Header */}
      <div className="flex flex-col md:flex-row items-center justify-between border-b border-slate-800 pb-6 mb-8 gap-4">
        <div className="flex items-center gap-4">
          <div className="w-16 h-16 rounded-2xl bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center text-cyan-400">
            <Award className="w-8 h-8" />
          </div>
          <div>
            <span className="text-xs font-mono text-cyan-400 uppercase tracking-wider">Lesson Complete</span>
            <h2 className="text-2xl font-bold text-white">{report.topic}</h2>
          </div>
        </div>

        {/* Score Badge */}
        <div className="text-center bg-slate-950 px-6 py-3 rounded-2xl border border-slate-800">
          <div className="text-3xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-emerald-400">
            {report.score_percentage}%
          </div>
          <div className="text-[11px] font-mono text-slate-400 uppercase">Concept Mastery Score</div>
        </div>
      </div>

      {/* Grid: Strengths vs Weaknesses */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
        {/* Strong concepts */}
        <div className="bg-slate-950/80 p-6 rounded-2xl border border-emerald-500/30">
          <div className="flex items-center gap-2 text-emerald-400 font-semibold text-sm mb-4">
            <CheckCircle className="w-4 h-4" />
            <span>Mastered Principles ({report.strong_concepts.length})</span>
          </div>
          <ul className="space-y-2.5">
            {report.strong_concepts.map((concept, i) => (
              <li key={i} className="text-xs md:text-sm text-slate-200 flex items-center gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                {concept}
              </li>
            ))}
          </ul>
        </div>

        {/* Weak concepts / Misconceptions */}
        <div className="bg-slate-950/80 p-6 rounded-2xl border border-amber-500/30">
          <div className="flex items-center gap-2 text-amber-400 font-semibold text-sm mb-4">
            <AlertCircle className="w-4 h-4" />
            <span>Remediated Misconceptions ({report.weak_concepts.length})</span>
          </div>
          {report.weak_concepts.length > 0 ? (
            <ul className="space-y-2.5">
              {report.weak_concepts.map((concept, i) => (
                <li key={i} className="text-xs md:text-sm text-amber-200 flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-amber-400" />
                  {concept}
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-xs text-slate-400 italic">No recurring misconceptions detected. Outstanding conceptual clarity!</p>
          )}
        </div>
      </div>

      {/* 7-Day Spaced Repetition Roadmap */}
      <div className="mb-8 bg-slate-950/90 p-6 rounded-2xl border border-slate-800">
        <div className="flex items-center gap-2 text-cyan-400 font-semibold text-sm mb-4">
          <Calendar className="w-4 h-4" />
          <span>7-Day Adaptive Spaced Retention Plan</span>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
          {report.seven_day_plan.map((item) => (
            <div
              key={item.day}
              onClick={() => toggleDay(item.day)}
              className={`p-3.5 rounded-xl border text-xs cursor-pointer transition-all ${
                completedDays.includes(item.day)
                  ? "border-emerald-500/50 bg-emerald-950/30 text-emerald-300"
                  : "border-slate-800 bg-slate-900/60 text-slate-300 hover:border-slate-700"
              }`}
            >
              <div className="flex items-center justify-between mb-1.5">
                <span className="font-mono font-bold text-cyan-400">Day {item.day}</span>
                <span className="text-[10px] text-slate-500">
                  {completedDays.includes(item.day) ? "Completed" : "Pending"}
                </span>
              </div>
              <p className="text-[11px] leading-relaxed">{item.task}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-slate-800">
        <button
          onClick={handleDownloadNotes}
          className="w-full sm:w-auto px-6 py-3.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-medium text-xs md:text-sm flex items-center justify-center gap-2 border border-slate-700 transition"
        >
          <Download className="w-4 h-4 text-cyan-400" />
          Download Full Blackboard Notes & Report
        </button>

        <button
          onClick={onRestart}
          className="w-full sm:w-auto px-8 py-3.5 rounded-xl bg-gradient-to-r from-cyan-500 to-indigo-600 font-bold text-white text-xs md:text-sm shadow-lg shadow-cyan-500/20 hover:brightness-110 transition flex items-center justify-center gap-2"
        >
          <span>Teach Another Topic / Chapter</span>
          <ArrowRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
};
